kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-role
rules:
  - apiGroups: [""]
    resources: ["pods","services","configmaps","secrets","ingresses"]
    verbs: ["get", "watch", "list","patch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-rolebinding
subjects:
  - kind: ServiceAccount
    name: control-panel-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: edit-role
  apiGroup: rbac.authorization.k8s.io