{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "config-poc.serviceAccountName" . }}
  labels:
    {{- include "config-poc.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---

  {{- if .Values.controlPanel.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "controlPanel.serviceAccountName" . }}
  labels:
    {{- include "controlPanel.labels" . | nindent 4 }}
  {{- with .Values.controlPanel.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
